[global]
api_key = ""
base_url = ""

[openai]
model = "gpt-4"
api_key = "your-openai-key"
base_url = "https://api.openai.com/v1"
temperature = 0.7
max_tokens = 2048
stream = false

[qwen]
model = "qwen-plus"
api_key = "sk-547b7f1fb2b0424f8c5e78ca3350f198"
base_url = "https://dashscope.aliyuncs.com/compatible-mode/v1"
temperature = 0.7
max_tokens = 1024
stream = false

[deepseek]
model = "deepseek-chat"
api_key = ""
base_url = "https://api.deepseek.com/v1"
temperature = 0.7
max_tokens = 1024
stream = false
